# Generated by Django 5.2.8 on 2025-11-12 04:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя артиста')),
                ('description', models.TextField(verbose_name='Описание артиста')),
                ('image', models.URLField(verbose_name='Фото артиста')),
                ('genre', models.CharField(blank=True, max_length=50, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Артист',
                'verbose_name_plural': 'Артисты',
                'indexes': [models.Index(fields=['name'], name='hello_app_a_name_a1ab5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория билета',
                'verbose_name_plural': 'Категории билетов',
                'indexes': [models.Index(fields=['name'], name='hello_app_c_name_639cd4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Начало')),
                ('end_time', models.DateTimeField(verbose_name='Конец')),
                ('description', models.TextField(blank=True, verbose_name='Описание концерта')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.artist', verbose_name='Артист')),
            ],
            options={
                'verbose_name': 'Концерт',
                'verbose_name_plural': 'Концерты',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=50, verbose_name='Должность')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['price'],
                'indexes': [models.Index(fields=['post'], name='hello_app_p_post_8baa3d_idx'), models.Index(fields=['price'], name='hello_app_p_price_816de1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('father_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.post', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name', 'father_name'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.TimeField(verbose_name='Часы работы')),
                ('concert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.concert', verbose_name='Концерт')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.staff', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата продажи')),
                ('quantity', models.IntegerField(verbose_name='Количество доступных')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.category', verbose_name='Категория')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.concert', verbose_name='Концерт')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя покупателя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('ticket_type', models.CharField(choices=[('dancefloor', 'Танцпол'), ('fan-zone', 'Фан-зона'), ('vip', 'VIP')], max_length=20, verbose_name='Тип билета')),
                ('quantity', models.IntegerField(verbose_name='Количество билетов')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заказа')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Номер заказа')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.concert', verbose_name='Концерт')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.ticket', verbose_name='Выбранный билет')),
            ],
            options={
                'verbose_name': 'Заказ билета',
                'verbose_name_plural': 'Заказы билетов',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название площадки')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
                'indexes': [models.Index(fields=['city'], name='hello_app_v_city_d83140_idx'), models.Index(fields=['name'], name='hello_app_v_name_19f864_idx')],
            },
        ),
        migrations.AddField(
            model_name='concert',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.venue', verbose_name='Площадка'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['first_name'], name='hello_app_s_first_n_ffc39f_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['last_name'], name='hello_app_s_last_na_1f3354_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['phone_number'], name='hello_app_s_phone_n_927438_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['hours'], name='hello_app_s_hours_1a2a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['price'], name='hello_app_t_price_ffa1e3_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['date'], name='hello_app_t_date_c2945a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketorder',
            index=models.Index(fields=['order_number'], name='hello_app_t_order_n_d1df9f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketorder',
            index=models.Index(fields=['customer_name'], name='hello_app_t_custome_c1b09f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketorder',
            index=models.Index(fields=['order_date'], name='hello_app_t_order_d_f7ab2b_idx'),
        ),
        migrations.AddIndex(
            model_name='concert',
            index=models.Index(fields=['start_time'], name='hello_app_c_start_t_b90072_idx'),
        ),
        migrations.AddIndex(
            model_name='concert',
            index=models.Index(fields=['end_time'], name='hello_app_c_end_tim_e196bd_idx'),
        ),
    ]
