# Generated by Django 5.2.7 on 2025-10-08 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'indexes': [models.Index(fields=['name'], name='hello_app_c_name_639cd4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Начало')),
                ('end_time', models.DateTimeField(verbose_name='Конец')),
            ],
            options={
                'verbose_name': 'Концерт',
                'verbose_name_plural': 'Концерты',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['start_time'], name='hello_app_c_start_t_b90072_idx'), models.Index(fields=['end_time'], name='hello_app_c_end_tim_e196bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=50, verbose_name='Должность')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['price'],
                'indexes': [models.Index(fields=['post'], name='hello_app_p_post_8baa3d_idx'), models.Index(fields=['price'], name='hello_app_p_price_816de1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('father_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.post', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name', 'father_name'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.TimeField(verbose_name='Часы')),
                ('concert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.concert', verbose_name='Концерт')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.staff', verbose_name='Сотрудник')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('date', models.DateField(verbose_name='Дата')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'ordering': ['price'],
            },
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['first_name'], name='hello_app_s_first_n_ffc39f_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['last_name'], name='hello_app_s_last_na_1f3354_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['phone_number'], name='hello_app_s_phone_n_927438_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['hours'], name='hello_app_s_hours_1a2a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['price'], name='hello_app_t_price_ffa1e3_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['date'], name='hello_app_t_date_c2945a_idx'),
        ),
    ]
